import React, { useState } from 'react';
import { StyleSheet, View, Text, ScrollView, TouchableOpacity, TextInput, Alert, Platform } from 'react-native';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Camera, FileText, Image as ImageIcon, Upload, X } from 'lucide-react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import { useLocalSearchParams } from 'expo-router';
import Colors from '@/constants/colors';
import Typography from '@/constants/typography';
import Header from '@/components/Header';
import Button from '@/components/Button';
import { useMedicalRecordsStore } from '@/store/medical-records-store';
import { useAuthStore } from '@/store/auth-store';

export default function UploadMedicalRecordScreen() {
  const router = useRouter();
  const { source } = useLocalSearchParams();
  const { user } = useAuthStore();
  const { uploadMedicalRecord, isLoading } = useMedicalRecordsStore();
  
  const [title, setTitle] = useState('');
  const [recordType, setRecordType] = useState<'lab' | 'imaging' | 'document'>('document');
  const [provider, setProvider] = useState('');
  const [fileSelected, setFileSelected] = useState(false);
  const [fileName, setFileName] = useState('');
  const [fileType, setFileType] = useState('');
  
  // Handle file selection based on source parameter if provided
  React.useEffect(() => {
    if (source === 'camera') {
      handleTakePhoto();
    } else if (source === 'file') {
      handleSelectFile();
    }
  }, [source]);
  
  const handleTakePhoto = async () => {
    try {
      const permissionResult = await ImagePicker.requestCameraPermissionsAsync();
      
      if (permissionResult.granted === false) {
        Alert.alert("Permission Required", "You need to grant camera permissions to take a photo.");
        return;
      }
      
      const result = await ImagePicker.launchCameraAsync({
        mediaTypes: ImagePicker.MediaTypeOptions.Images,
        allowsEditing: true,
        quality: 0.8,
      });
      
      if (!result.canceled) {
        const asset = result.assets[0];
        setFileSelected(true);
        setFileName(asset.fileName || 'camera_image.jpg');
        setFileType('image/jpeg');
      }
    } catch (error) {
      console.error("Error taking photo:", error);
      Alert.alert("Error", "There was an error taking a photo. Please try again.");
    }
  };
  
  const handleSelectFile = async () => {
    try {
      const result = await DocumentPicker.getDocumentAsync({
        type: ['application/pdf', 'image/*'],
        copyToCacheDirectory: true,
      });
      
      if (result.canceled === false) {
        const asset = result.assets[0];
        setFileSelected(true);
        setFileName(asset.name);
        setFileType(asset.mimeType || '');
      }
    } catch (error) {
      console.error("Error selecting file:", error);
      Alert.alert("Error", "There was an error selecting a file. Please try again.");
    }
  };
  
  const handleUpload = async () => {
    if (!title) {
      Alert.alert("Missing Information", "Please provide a title for your document.");
      return;
    }
    
    if (!fileSelected) {
      Alert.alert("No File Selected", "Please select a file to upload.");
      return;
    }
    
    if (!user) {
      Alert.alert("Authentication Error", "You must be logged in to upload documents.");
      return;
    }
    
    const record = {
      patientId: user.id,
      type: recordType,
      title,
      date: new Date().toISOString(),
      provider: provider || 'Self-uploaded',
      fileType,
      id: `record-${Date.now()}`, // In a real app, this would be generated by the server
    };
    
    const success = await uploadMedicalRecord(record);
    
    if (success) {
      Alert.alert(
        "Upload Successful", 
        "Your medical record has been uploaded successfully.",
        [{ text: "OK", onPress: () => router.back() }]
      );
    } else {
      Alert.alert("Upload Failed", "There was an error uploading your document. Please try again.");
    }
  };
  
  const handleCancel = () => {
    router.back();
  };
  
  const getRecordTypeIcon = (type: string) => {
    switch (type) {
      case 'lab':
        return <FileText size={20} color={Colors.danger} />;
      case 'imaging':
        return <ImageIcon size={20} color={Colors.info} />;
      case 'document':
        return <FileText size={20} color={Colors.success} />;
      default:
        return <FileText size={20} color={Colors.textSecondary} />;
    }
  };

  return (
    <SafeAreaView style={styles.container} edges={['bottom', 'left', 'right']}>
      <Header title="Upload Medical Record" />
      
      <ScrollView contentContainerStyle={styles.scrollContent}>
        <View style={styles.formSection}>
          <Text style={styles.sectionLabel}>Document Title*</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter document title"
            value={title}
            onChangeText={setTitle}
          />
        </View>
        
        <View style={styles.formSection}>
          <Text style={styles.sectionLabel}>Document Type</Text>
          <View style={styles.recordTypeContainer}>
            <TouchableOpacity 
              style={[
                styles.recordTypeButton,
                recordType === 'document' && styles.recordTypeButtonActive,
              ]}
              onPress={() => setRecordType('document')}
            >
              {getRecordTypeIcon('document')}
              <Text 
                style={[
                  styles.recordTypeText,
                  recordType === 'document' && styles.recordTypeTextActive,
                ]}
              >
                Document
              </Text>
            </TouchableOpacity>
            
            <TouchableOpacity 
              style={[
                styles.recordTypeButton,
                recordType === 'lab' && styles.recordTypeButtonActive,
              ]}
              onPress={() => setRecordType('lab')}
            >
              {getRecordTypeIcon('lab')}
              <Text 
                style={[
                  styles.recordTypeText,
                  recordType === 'lab' && styles.recordTypeTextActive,
                ]}
              >
                Lab Result
              </Text>
            </TouchableOpacity>
            
            <TouchableOpacity 
              style={[
                styles.recordTypeButton,
                recordType === 'imaging' && styles.recordTypeButtonActive,
              ]}
              onPress={() => setRecordType('imaging')}
            >
              {getRecordTypeIcon('imaging')}
              <Text 
                style={[
                  styles.recordTypeText,
                  recordType === 'imaging' && styles.recordTypeTextActive,
                ]}
              >
                Imaging
              </Text>
            </TouchableOpacity>
          </View>
        </View>
        
        <View style={styles.formSection}>
          <Text style={styles.sectionLabel}>Healthcare Provider (Optional)</Text>
          <TextInput
            style={styles.input}
            placeholder="Enter provider name"
            value={provider}
            onChangeText={setProvider}
          />
        </View>
        
        <View style={styles.formSection}>
          <Text style={styles.sectionLabel}>Upload File*</Text>
          
          {fileSelected ? (
            <View style={styles.selectedFileContainer}>
              <View style={styles.selectedFileInfo}>
                <FileText size={24} color={Colors.primary} />
                <View style={styles.fileNameContainer}>
                  <Text style={styles.fileName} numberOfLines={1} ellipsizeMode="middle">
                    {fileName}
                  </Text>
                  <Text style={styles.fileType}>{fileType}</Text>
                </View>
              </View>
              <TouchableOpacity 
                style={styles.removeFileButton}
                onPress={() => {
                  setFileSelected(false);
                  setFileName('');
                  setFileType('');
                }}
              >
                <X size={20} color={Colors.textSecondary} />
              </TouchableOpacity>
            </View>
          ) : (
            <View style={styles.uploadOptions}>
              <TouchableOpacity 
                style={styles.uploadOption}
                onPress={handleTakePhoto}
              >
                <View style={styles.uploadIconContainer}>
                  <Camera size={24} color={Colors.primary} />
                </View>
                <Text style={styles.uploadOptionText}>Take Photo</Text>
              </TouchableOpacity>
              
              <TouchableOpacity 
                style={styles.uploadOption}
                onPress={handleSelectFile}
              >
                <View style={styles.uploadIconContainer}>
                  <Upload size={24} color={Colors.primary} />
                </View>
                <Text style={styles.uploadOptionText}>Select File</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
        
        <View style={styles.privacyNote}>
          <Text style={styles.privacyNoteText}>
            Your medical records are encrypted and stored securely. Only you can access them unless you explicitly share them with a healthcare provider.
          </Text>
        </View>
      </ScrollView>
      
      <View style={styles.footer}>
        <Button
          title="Cancel"
          onPress={handleCancel}
          variant="secondary"
          style={styles.footerButton}
        />
        <Button
          title="Upload Document"
          onPress={handleUpload}
          loading={isLoading}
          style={styles.footerButton}
        />
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  scrollContent: {
    padding: 16,
  },
  formSection: {
    marginBottom: 24,
  },
  sectionLabel: {
    ...Typography.label,
    marginBottom: 8,
  },
  input: {
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingVertical: 12,
    ...Typography.body,
  },
  recordTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  recordTypeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    paddingVertical: 12,
    marginHorizontal: 4,
  },
  recordTypeButtonActive: {
    backgroundColor: Colors.primaryLight,
    borderColor: Colors.primary,
  },
  recordTypeText: {
    ...Typography.body,
    marginLeft: 8,
    color: Colors.textSecondary,
  },
  recordTypeTextActive: {
    color: Colors.primary,
    fontWeight: '500',
  },
  uploadOptions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  uploadOption: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    padding: 16,
    marginHorizontal: 4,
  },
  uploadIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: Colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  uploadOptionText: {
    ...Typography.body,
    color: Colors.text,
  },
  selectedFileContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.card,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: 8,
    padding: 16,
  },
  selectedFileInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  fileNameContainer: {
    marginLeft: 12,
    flex: 1,
  },
  fileName: {
    ...Typography.body,
    fontWeight: '500',
  },
  fileType: {
    ...Typography.caption,
    color: Colors.textSecondary,
  },
  removeFileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.secondary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  privacyNote: {
    backgroundColor: Colors.primaryLight,
    borderRadius: 8,
    padding: 16,
    marginBottom: 24,
  },
  privacyNoteText: {
    ...Typography.caption,
    color: Colors.textSecondary,
  },
  footer: {
    flexDirection: 'row',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.background,
  },
  footerButton: {
    flex: 1,
    marginHorizontal: 4,
  },
});